### ISSUE TITLE
Arctos getting a 404 when looking for GloBI stuff

### ISSUE THREAD

**Issue by Jegelewicz** [globalbioticinteractions/globalbioticinteractions.github.io#101] opened 2022-09-01 22:22 UTC
@jhpoelen see https://github.com/ArctosDB/arctos/issues/4998#issue-1359316806

**Comment by jhpoelen** [comment] 2022-09-01 22:45
@Jegelewicz thanks for letting me know. I investigated and reported in https://github.com/ArctosDB/arctos/issues/4998#issuecomment-1234852754 . Waiting for your reply.

**Comment by jhpoelen** [comment] 2022-09-02 17:57
closing this issue as duplicate of https://github.com/ArctosDB/arctos/issues/4998#issuecomment-1234852754

**Closed by jhpoelen** 2022-09-02 17:57 UTC
