### ISSUE TITLE
Bug(?) - interface pivots between names shown, and finds no interactions

### ISSUE THREAD

**Issue by mjy** [globalbioticinteractions/globalbioticinteractions.github.io#66] opened 2018-11-20 20:39 UTC
```
When I browse to list of interactions
    then I see a taxon name (Apis mellifera)
    when I click to expand that record
        then I see a different taxon name (Apis mellifera scutellata)
           which is a little odd
              then I click that I get "no interaction found"
                 which seems odd, because where did I come from?
```

<img width="341" alt="screen shot 2018-11-20 at 10 29 27 am" src="https://user-images.githubusercontent.com/22600/48801353-bdb6e480-ecd1-11e8-810d-cb671b02bc39.png">

<img width="1305" alt="screen shot 2018-11-20 at 10 29 43 am" src="https://user-images.githubusercontent.com/22600/48801394-e63ede80-ecd1-11e8-976f-e65be6387b6a.png">

**Comment by jhpoelen** [comment] 2018-11-20 21:58
Interesting! Could you share the GloBI url for the unexpected results?

**Comment by jhpoelen** [comment] 2018-11-21 01:35
@mjy I had a look at the suspicious behavior and found that the root cause is a mapping bug in v0.3.8 of GloBI taxon map at http://doi.org/10.5281/zenodo.1489121 .

```curl --silent "https://zenodo.org/record/1489121/files/taxonMap.tsv.gz" | gunzip | grep "Apis mellifera scutellata" ``` produces (header added):

providedTaxonId | providedTaxonName | resolvedTaxonId | resolvedTaxonName
-- | -- | -- | --
EOL:10455995 |   | EOL:10455995 | Apis mellifera scutellata
EOL:10455995 |   | INAT_TAXON:121322 | Apis mellifera scutellata
EOL:10455995 |   | NCBI:212527 | Apis mellifera scutellata
EOL:10455995 |   | OTT:85741 | Apis mellifera scutellata
EOL:10455995 |   | WD:Q2034820 | Apis mellifera scutellata
INAT_TAXON:121322 | Apis mellifera scutellata | GBIF:1341976 | Apis mellifera
INAT_TAXON:121322 | Apis mellifera scutellata | INAT_TAXON:47219 | Apis mellifera
INAT_TAXON:121322 | Apis mellifera scutellata | IRMNG:11307057 | Apis mellifera
INAT_TAXON:121322 | Apis mellifera scutellata | ITIS:154396 | Apis mellifera
INAT_TAXON:121322 | Apis mellifera scutellata | NBN:NHMSYS0000875423 | Apis mellifera
INAT_TAXON:121322 | Apis mellifera scutellata | NCBI:7460 | Apis mellifera
INAT_TAXON:121322 | Apis mellifera scutellata | OTT:461645 | Apis mellifera
INAT_TAXON:121322 | Apis mellifera scutellata | WD:Q30034 | Apis mellifera

which shows that subspecies ```Apis mellifera scutellata```` was mapped to its species name. The underlying cause it expected to be a rate limit exception of the API used (in this case iNaturalist) which prompted another attempt to match the name by its species, which then succeeded. Rate limits make perfect sense to protect a system, but does impose difficulties for continuous batch processes like those used in GloBI. 

I am planning to re-map the said names (and similar mapping errors) and include the corrections in the next version of GloBI's taxon graph. Will keep this issue open until the changes have propagated.

Am open to suggestions on how to improve this taxon name linking business.

Thanks for reporting and your patience.

**Comment by jhpoelen** [comment] 2019-09-20 18:38
@mjy Just revisited the Apis millifera vs. Apis mellifera scutellata name mapping bug . I've narrowed the criteria for selecting matching taxa to avoid including subspecies names that were matched to species taxa. Regardless, the GloBI taxon map could use some TLC. 

After applying the changes, the expected results are displayed:

so instead of

When I browse to list of interactions
    then I see a taxon name (Apis mellifera)
    when I click to expand that record
        then I see a different taxon name (Apis mellifera scutellata)
           which is a little odd
              then I click that I get "no interaction found"
                 which seems odd, because where did I come from?

now:

When I browse to list of interactions
    then I see a taxon name (Apis mellifera)
    when I click to expand that record
        then I see a different taxon name (Apis mellifera)
              then I click that I get an expected non-empty list of related interactions

See attached screenshots.

![Screenshot from 2019-09-20 11-30-58](https://user-images.githubusercontent.com/1084872/65350650-09a91300-db9b-11e9-8031-6cde694f4255.png)
![Screenshot from 2019-09-20 11-31-22](https://user-images.githubusercontent.com/1084872/65350663-10378a80-db9b-11e9-861a-a3f76fea8422.png)

Closing issue, but please do holler / comment if you believe this issue has not been resolved.

**Closed by jhpoelen** 2019-09-20 18:38 UTC
Labels: bug, taxon mapping
